'use strict';
/* CFOP 頂層公式表（OLL 57 式 + PLL 21 式）
   採標準算法；求解時用「套用後驗證」辨識，保證正確，不依賴命名精準。 */
(function () {

  // ---------- PLL（21 式）----------
  const PLL = [
    { name: 'Aa', alg: "R' F R' B2 R F' R' B2 R2" },
    { name: 'Ab', alg: "R2 B2 R F R' B2 R F' R" },
    { name: 'E',  alg: "x' L' U L D' L' U' L D L' U' L D' L' U L D" },
    { name: 'Ua', alg: "R U' R U R U R U' R' U' R2" },
    { name: 'Ub', alg: "R2 U R U R' U' R' U' R' U R'" },
    { name: 'H',  alg: "M2 U M2 U2 M2 U M2" },
    { name: 'Z',  alg: "M2 U M2 U M' U2 M2 U2 M'" },
    { name: 'Ja', alg: "R' U L' U2 R U' R' U2 R L" },
    { name: 'Jb', alg: "R U R' F' R U R' U' R' F R2 U' R' U'" },
    { name: 'T',  alg: "R U R' U' R' F R2 U' R' U' R U R' F'" },
    { name: 'Ra', alg: "R U' R' U' R U R D R' U' R D' R' U2 R'" },
    { name: 'Rb', alg: "R' U2 R U2 R' F R U R' U' R' F' R2" },
    { name: 'F',  alg: "R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R" },
    { name: 'Ga', alg: "R2 U R' U R' U' R U' R2 U' D R' U R D'" },
    { name: 'Gb', alg: "R' U' R U D' R2 U R' U R U' R U' R2 D" },
    { name: 'Gc', alg: "R2 U' R U' R U R' U R2 U D' R U' R' D" },
    { name: 'Gd', alg: "R U R' U' D R2 U' R U' R' U R' U R2 D'" },
    { name: 'V',  alg: "R' U R' U' y R' F' R2 U' R' U R' F R F" },
    { name: 'Y',  alg: "F R U' R' U' R U R' F' R U R' U' R' F R F'" },
    { name: 'Na', alg: "R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'" },
    { name: 'Nb', alg: "R' U R U' R' F' U' F R U R' F R' F' R U' R" },
  ];

  // ---------- OLL（57 式）----------
  const OLL = [
    { n: 1,  name: 'Dot',   alg: "R U2 R2 F R F' U2 R' F R F'" },
    { n: 2,  name: 'Dot',   alg: "F R U R' U' F' f R U R' U' f'" },
    { n: 3,  name: 'Dot',   alg: "f R U R' U' f' U' F R U R' U' F'" },
    { n: 4,  name: 'Dot',   alg: "f R U R' U' f' U F R U R' U' F'" },
    { n: 5,  name: 'SLBS',  alg: "r' U2 R U R' U r" },
    { n: 6,  name: 'SLBS',  alg: "r U2 R' U' R U' r'" },
    { n: 7,  name: 'WBS',   alg: "r U R' U R U2 r'" },
    { n: 8,  name: 'WBS',   alg: "r' U' R U' R' U2 r" },
    { n: 9,  name: 'Fish',  alg: "R U R' U' R' F R2 U R' U' F'" },
    { n: 10, name: 'Fish',  alg: "R U R' U R' F R F' R U2 R'" },
    { n: 11, name: 'SLBS',  alg: "r U R' U R' F R F' R U2 r'" },
    { n: 12, name: 'SLBS',  alg: "F R U R' U' F' U F R U R' U' F'" },
    { n: 13, name: 'Knight',alg: "F U R U' R2 F' R U R U' R'" },
    { n: 14, name: 'Knight',alg: "R' F R U R' F' R F U' F'" },
    { n: 15, name: 'SLBS',  alg: "l' U' l L' U' L U l' U l" },
    { n: 16, name: 'SLBS',  alg: "r U r' R U R' U' r U' r'" },
    { n: 17, name: 'Dot',   alg: "F R' F' R2 r' U R U' R' U' M'" },
    { n: 18, name: 'Dot',   alg: "r U R' U R U2 r2 U' R U' R' U2 r" },
    { n: 19, name: 'Dot',   alg: "r' R U R U R' U' M' R' F R F'" },
    { n: 20, name: 'Dot',   alg: "r U R' U' M2 U R U' R' U' M'" },
    { n: 21, name: 'H (雙小魚)',  alg: "R U2 R' U' R U R' U' R U' R'" },
    { n: 22, name: 'Pi (牛頭)',  alg: "R U2 R2 U' R2 U' R2 U2 R" },
    { n: 23, name: 'Headlights (雙燈)',  alg: "R2 D R' U2 R D' R' U2 R'" },
    { n: 24, name: 'T',  alg: "r U R' U' r' F R F'" },
    { n: 25, name: 'Bowtie (領結)',  alg: "F' r U R' U' r' F R" },
    { n: 26, name: 'Antisune (反小魚)',  alg: "R U2 R' U' R U' R'" },
    { n: 27, name: 'Sune (小魚)',  alg: "R U R' U R U2 R'" },
    { n: 28, name: 'Awkward',alg: "r U R' U' r' R U R U' R'" },
    { n: 29, name: 'Awkward',alg: "R U R' U' R U' R' F' U' F R U R'" },
    { n: 30, name: 'Awkward',alg: "F R' F R2 U' R' U' R U R' F2" },
    { n: 31, name: 'P',     alg: "R' U' F U R U' R' F' R" },
    { n: 32, name: 'P',     alg: "L U F' U' L' U L F L'" },
    { n: 33, name: 'T',     alg: "R U R' U' R' F R F'" },
    { n: 34, name: 'C',     alg: "R U R2 U' R' F R U R U' F'" },
    { n: 35, name: 'Fish',  alg: "R U2 R2 F R F' R U2 R'" },
    { n: 36, name: 'WBS',   alg: "L' U' L U' L' U L U L F' L' F" },
    { n: 37, name: 'Fish',  alg: "F R' F' R U R U' R'" },
    { n: 38, name: 'WBS',   alg: "R U R' U R U' R' U' R' F R F'" },
    { n: 39, name: 'BLBS',  alg: "L F' L' U' L U F U' L'" },
    { n: 40, name: 'BLBS',  alg: "R' F R U R' U' F' U R" },
    { n: 41, name: 'Awkward',alg: "R U R' U R U2 R' F R U R' U' F'" },
    { n: 42, name: 'Awkward',alg: "R' U' R U' R' U2 R F R U R' U' F'" },
    { n: 43, name: 'P',     alg: "F' U' L' U L F" },
    { n: 44, name: 'P',     alg: "F U R U' R' F'" },
    { n: 45, name: 'T',     alg: "F R U R' U' F'" },
    { n: 46, name: 'C',     alg: "R' U' R' F R F' U R" },
    { n: 47, name: 'BLBS',  alg: "F' L' U' L U L' U' L U F" },
    { n: 48, name: 'BLBS',  alg: "F R U R' U' R U R' U' F'" },
    { n: 49, name: 'BLBS',  alg: "r U' r2 U r2 U r2 U' r" },
    { n: 50, name: 'BLBS',  alg: "r' U r2 U' r2 U' r2 U r'" },
    { n: 51, name: 'Line',  alg: "F U R U' R' U R U' R' F'" },
    { n: 52, name: 'Line',  alg: "R U R' U R U' B U' B' R'" },
    { n: 53, name: 'Knight',alg: "l' U2 L U L' U' L U L' U l" },
    { n: 54, name: 'Knight',alg: "r U2 R' U' R U R' U' R U' r'" },
    { n: 55, name: 'Line',  alg: "R' F R U R U' R2 F' R2 U' R' U R U R'" },
    { n: 56, name: 'Line',  alg: "r U r' U R U' R' U R U' R' r U' r'" },
    { n: 57, name: 'H',     alg: "R U R' U' M' U R U' r'" },
  ];

  const _exports = { PLL, OLL };
  if (typeof module !== 'undefined' && module.exports) module.exports = _exports;
  if (typeof window !== 'undefined') window.CFOP_ALGS = _exports;
})();
